// noinspection ES6PreferShortImport
import { defaultStore } from '../store/defaultStore';
import { SupabaseProvider } from '@/hooks/useSupabaseBrowser';
import '@/styles/globals.css';
import { ChakraProvider, extendTheme } from '@chakra-ui/react';
import { QueryClient } from '@tanstack/query-core';
import { QueryClientProvider } from '@tanstack/react-query';
import { Provider } from 'jotai';
import type { AppProps } from 'next/app';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
  const theme = extendTheme({ initialColorMode: 'dark' });
  const queryClient = new QueryClient();

  return (
    <>
      <Head>
        <title>Swiss Card Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SupabaseProvider>
        <QueryClientProvider client={queryClient}>
          <ChakraProvider theme={theme}>
            <Provider store={defaultStore}>
              <Component {...pageProps} />
            </Provider>
          </ChakraProvider>
        </QueryClientProvider>
      </SupabaseProvider>
    </>
  );
}
