-- noinspection SqlNoDataSourceInspectionForFile
-- noinspection SqlResolveForFile @ any/"auth"

CREATE TABLE products
(
    id          bigint generated by default as identity primary key,
    title text,
    content text,
    inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- use this to insert data
-- insert into public.products VALUES (1, 'title', 'content');

alter table products enable row level security;

create
policy "Logged in users can create products." on products for
   insert with check (auth.uid() is not null);

create
policy "Logged in users can update products." on products for
update using (auth.uid() is not null);

create
policy "Logged in users can delete products." on products for
   delete
using (auth.uid() is not null);

create
policy "notices are public." on products for
select using (true);
