name: "CI"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: "Lint app"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
        working-directory: app

      - run: npm run build
        working-directory: app

      - run: npm run lint-check
        working-directory: app

  e2e:
    name: "e2e tests"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.0
        with:
          key: docker-${{ runner.os }}

      - name: Copy .env file
        run: cp .env.example .env.local
        working-directory: app

      - run: npm ci
        working-directory: app

      - name: Supabase start
        run: npm run supabase start
        working-directory: app

      - run: npm run build
        working-directory: app

      - run: npm run dev &
        working-directory: app

      - run: npm run cypress-run
        working-directory: app

  component:
    name: "component tests"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
        working-directory: app

      - run: npm run build
        working-directory: app

      - run: npm run dev &
        working-directory: app

      - run: npm run cypress-run-components
        working-directory: app
