-- noinspection SqlNoDataSourceInspectionForFile
-- noinspection SqlResolveForFile @ any/"auth"

CREATE TABLE products
(
    id          bigint generated by default as identity primary key,
    title       text,
    description text,
    rarity      varchar(30),
    set         text,
    card_type   varchar(30),
    attributes  varchar(100),
    types       varchar(100),
    price       float,
    inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
    created_at  timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table products
    enable row level security;

create
    policy "Logged in users can create products." on products for
    insert with check (true);

create
    policy "Logged in users can update products." on products for
    update using (true);

create
    policy "Logged in users can delete products." on products for
    delete
    using (true);

create
    policy "notices are public." on products for
    select using (true);
